#!/usr/bin/env python3
"""
Test Close CRM staging integration (NO actual email/SMS sends!)

Usage:
    # First, set test lead ID
    export TEST_CLOSE_LEAD_ID="lead_kHqEeFNq8lnZmuHZqoyaQLd0S813DyAoZTTXCpNnZOf"

    # Run tests
    python test_staging_integration.py

SAFETY:
    - Tests with 2-3 leads only (well under rate limits)
    - Uses NOTES only (cannot trigger sends)
    - All content clearly marked as "STAGED - NOT SENT"
"""
import asyncio
import os
import sys
from datetime import datetime

# Add backend to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Load environment variables
from dotenv import load_dotenv
load_dotenv()


async def test_staging_service_direct():
    """
    TEST 1: Test the CloseStagingService directly (1 API call).

    This tests the staging service in isolation before testing
    the full pipeline integration.
    """
    print("\n" + "="*60)
    print("TEST 1: Close CRM Staging Service (Direct)")
    print("="*60)

    from app.services.crm.close_staging import CloseStagingService

    # Check environment
    if not os.getenv("CLOSE_API_KEY"):
        print("ERROR: CLOSE_API_KEY not set!")
        return False

    test_lead_id = os.getenv("TEST_CLOSE_LEAD_ID")
    if not test_lead_id:
        print("ERROR: TEST_CLOSE_LEAD_ID not set!")
        print("   Set this to a real Close CRM lead ID")
        print("   Example: export TEST_CLOSE_LEAD_ID=lead_kHqEeFNq8lnZmuHZqoyaQLd0S813DyAoZTTXCpNnZOf")
        return False

    # First verify the lead exists
    staging = CloseStagingService()
    print(f"Verifying lead exists: {test_lead_id[:20]}...")

    lead_exists = await staging.check_lead_exists(test_lead_id)
    if not lead_exists:
        print(f"ERROR: Lead {test_lead_id} not found in Close CRM!")
        print("   Make sure the lead ID is correct and the lead exists.")
        return False

    print(f"Lead verified!")

    # Test marketing content
    marketing_content = {
        "email_subject": f"[TEST] Sales Agent Pipeline Test - {datetime.now().strftime('%H:%M:%S')}",
        "email_content": f"""Hi there,

This is a TEST email generated by the sales-agent pipeline.
Timestamp: {datetime.now().isoformat()}

This content was staged as a NOTE in Close CRM - NOT actually sent.
It is for review and manual sending only.

Best regards,
Sales Agent Pipeline (Test Mode)""",
        "sms_content": f"[TEST] Sales-agent pipeline test at {datetime.now().strftime('%H:%M:%S')}. This is staged, not sent."
    }

    print(f"Staging content to lead: {test_lead_id[:30]}...")
    result = await staging.stage_marketing_content(
        lead_id=test_lead_id,
        marketing_content=marketing_content
    )

    if result.get("note", {}).get("success"):
        activity_id = result['note'].get('activity_id')
        print(f"SUCCESS! Note created: {activity_id}")
        print(f"   Check Close CRM to see the staged content!")
        return True
    else:
        print(f"FAILED: {result}")
        return False


async def test_pipeline_with_staging():
    """
    TEST 2: Test full pipeline with staging option enabled (2-3 leads).

    This tests the complete pipeline flow:
    Qualification -> CRM Check -> Enrichment -> Marketing -> STAGING -> Dedup -> CRM
    """
    print("\n" + "="*60)
    print("TEST 2: Full Pipeline with Staging (LIMITED TO 2-3 LEADS)")
    print("="*60)

    test_lead_id = os.getenv("TEST_CLOSE_LEAD_ID")
    if not test_lead_id:
        print("ERROR: TEST_CLOSE_LEAD_ID not set!")
        return False

    # Import pipeline components
    from app.services.pipeline_orchestrator import PipelineOrchestrator
    from app.schemas.pipeline import PipelineTestRequest, PipelineTestOptions

    orchestrator = PipelineOrchestrator()

    # Test lead with Close CRM lead_id for staging
    test_lead = {
        "name": "Prime Star Property Solutions LLC",
        "company_name": "Prime Star Property Solutions LLC",
        "website": "primestarproperties.com",
        "industry": "Property Management",
        "close_lead_id": test_lead_id,  # Required for staging!
    }

    print(f"\nProcessing: {test_lead['company_name']}")
    print(f"   Lead ID: {test_lead_id[:30]}...")

    try:
        result = await orchestrator.execute(
            PipelineTestRequest(
                lead=test_lead,
                options=PipelineTestOptions(
                    stop_on_duplicate=False,
                    skip_enrichment=True,  # Skip for faster testing
                    generate_marketing=True,  # Generate marketing content
                    create_in_crm=False,  # Don't create in CRM
                    dry_run=True,  # Dry run mode
                    stage_to_crm=True,  # ENABLE STAGING!
                )
            )
        )

        print(f"\n--- Pipeline Results ---")
        print(f"   Success: {result.success}")
        print(f"   Total Latency: {result.total_latency_ms}ms")
        print(f"   Total Cost: ${result.total_cost_usd:.6f}")
        print(f"\n   Stages:")
        for stage_name, stage_result in result.stages.items():
            status = stage_result.status
            latency = stage_result.latency_ms or 0
            status_icon = "GREEN_CHECK" if status in ["success", "completed", "skipped"] else "RED_X"
            print(f"      {status_icon} {stage_name}: {status} ({latency}ms)")

            # Show staging details
            if stage_name == "staging" and stage_result.output:
                activity_id = stage_result.output.get("activity_id", "N/A")
                print(f"         Activity ID: {activity_id}")

        # Check if staging succeeded
        staging_stage = result.stages.get("staging")
        if staging_stage and staging_stage.status == "success":
            print(f"\nSUCCESS! Content staged in Close CRM")
            print(f"   Check the lead in Close CRM to see the staged note.")
            return True
        elif staging_stage and staging_stage.status == "skipped":
            print(f"\nSTAGING SKIPPED: {staging_stage.output}")
            return True  # Not a failure, just skipped
        else:
            print(f"\nSTAGING FAILED or NOT RUN")
            if staging_stage:
                print(f"   Status: {staging_stage.status}")
                print(f"   Error: {staging_stage.error}")
            return False

    except Exception as e:
        print(f"\nPIPELINE ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False


async def main():
    """Run all staging tests."""
    print("="*60)
    print("SALES AGENT - CLOSE CRM STAGING TEST")
    print("="*60)
    print(f"Timestamp: {datetime.now().isoformat()}")
    print()
    print("SAFETY MEASURES:")
    print("   - NO actual emails or SMS will be sent")
    print("   - Content staged as NOTES only (cannot trigger sends)")
    print("   - Testing with 2-3 leads only (well under rate limits)")
    print("="*60)

    # Check environment
    if not os.getenv("CLOSE_API_KEY"):
        print("\nERROR: CLOSE_API_KEY not set!")
        print("   Add CLOSE_API_KEY to your .env file")
        return

    if not os.getenv("TEST_CLOSE_LEAD_ID"):
        print("\nWARNING: TEST_CLOSE_LEAD_ID not set!")
        print("   Set this to a real Close CRM lead ID for testing")
        print("   Example: export TEST_CLOSE_LEAD_ID=lead_kHqEeFNq8lnZmuHZqoyaQLd0S813DyAoZTTXCpNnZOf")
        print()
        print("   Suggested test lead (Prime Star Property Solutions LLC):")
        print("   export TEST_CLOSE_LEAD_ID=lead_kHqEeFNq8lnZmuHZqoyaQLd0S813DyAoZTTXCpNnZOf")
        return

    # Run tests
    results = []

    # Test 1: Direct staging service test
    test1_passed = await test_staging_service_direct()
    results.append(("Direct Staging Service", test1_passed))

    if test1_passed:
        print("\n1 second delay before next test (rate limit safety)...")
        await asyncio.sleep(1)

        # Test 2: Full pipeline with staging
        test2_passed = await test_pipeline_with_staging()
        results.append(("Full Pipeline Staging", test2_passed))

    # Summary
    print("\n" + "="*60)
    print("TEST RESULTS SUMMARY")
    print("="*60)
    for test_name, passed in results:
        status = "PASSED" if passed else "FAILED"
        icon = "GREEN_CHECK" if passed else "RED_X"
        print(f"   {icon} {test_name}: {status}")

    all_passed = all(passed for _, passed in results)
    if all_passed:
        print("\nALL TESTS PASSED!")
        print("   Check Close CRM to see staged content.")
    else:
        print("\nSOME TESTS FAILED!")
        print("   Check the output above for details.")

    print("\n" + "="*60)
    print("DONE")
    print("="*60)


if __name__ == "__main__":
    asyncio.run(main())
