"""Initial schema: leads and cerebras_api_calls tables

Revision ID: 64e77371d123
Revises: 
Create Date: 2025-10-04 07:46:27.660366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e77371d123'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cerebras_api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('input_cost_usd', sa.Float(), nullable=True),
    sa.Column('output_cost_usd', sa.Float(), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerebras_api_calls_cache_hit'), 'cerebras_api_calls', ['cache_hit'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_created_at'), 'cerebras_api_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_endpoint'), 'cerebras_api_calls', ['endpoint'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_id'), 'cerebras_api_calls', ['id'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_model'), 'cerebras_api_calls', ['model'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_operation_type'), 'cerebras_api_calls', ['operation_type'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_success'), 'cerebras_api_calls', ['success'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_title', sa.String(length=200), nullable=True),
    sa.Column('qualification_score', sa.Float(), nullable=True),
    sa.Column('qualification_reasoning', sa.Text(), nullable=True),
    sa.Column('qualification_model', sa.String(length=100), nullable=True),
    sa.Column('qualification_latency_ms', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_name'), 'leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_leads_contact_email'), 'leads', ['contact_email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_qualification_score'), 'leads', ['qualification_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_qualification_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_name'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_cerebras_api_calls_success'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_operation_type'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_model'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_id'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_endpoint'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_created_at'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_cache_hit'), table_name='cerebras_api_calls')
    op.drop_table('cerebras_api_calls')
    # ### end Alembic commands ###
