"""Add multi-agent system models

Revision ID: af36f48fb48c
Revises: 64e77371d123
Create Date: 2025-10-04 14:38:40.902073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af36f48fb48c'
down_revision: Union[str, None] = '64e77371d123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='agent_execution_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_type'), 'agent_executions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_executions_id'), 'agent_executions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_executions_lead_id'), 'agent_executions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_executions_workflow_id'), 'agent_executions', ['workflow_id'], unique=False)
    op.create_table('agent_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='agent_workflow_status'), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_workflows_lead_id'), 'agent_workflows', ['lead_id'], unique=False)
    op.create_index(op.f('ix_agent_workflows_status'), 'agent_workflows', ['status'], unique=False)
    op.create_table('booked_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('calendar_link', sa.String(length=500), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('hubspot_meeting_id', sa.String(length=100), nullable=True),
    sa.Column('calendly_event_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_meetings_calendly_event_id'), 'booked_meetings', ['calendly_event_id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_hubspot_meeting_id'), 'booked_meetings', ['hubspot_meeting_id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_id'), 'booked_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_lead_id'), 'booked_meetings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_scheduled_time'), 'booked_meetings', ['scheduled_time'], unique=False)
    op.create_table('enriched_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.BigInteger(), nullable=True),
    sa.Column('funding_total', sa.BigInteger(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('decision_makers', sa.JSON(), nullable=True),
    sa.Column('enrichment_source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enriched_leads_id'), 'enriched_leads', ['id'], unique=False)
    op.create_index(op.f('ix_enriched_leads_lead_id'), 'enriched_leads', ['lead_id'], unique=True)
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('subject_lines', sa.JSON(), nullable=True),
    sa.Column('email_sequences', sa.JSON(), nullable=True),
    sa.Column('linkedin_messages', sa.JSON(), nullable=True),
    sa.Column('predicted_open_rate', sa.Float(), nullable=True),
    sa.Column('predicted_reply_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_campaigns_campaign_type'), 'marketing_campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_id'), 'marketing_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_lead_id'), 'marketing_campaigns', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_campaigns_lead_id'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_id'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_campaign_type'), table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_enriched_leads_lead_id'), table_name='enriched_leads')
    op.drop_index(op.f('ix_enriched_leads_id'), table_name='enriched_leads')
    op.drop_table('enriched_leads')
    op.drop_index(op.f('ix_booked_meetings_scheduled_time'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_lead_id'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_id'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_hubspot_meeting_id'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_calendly_event_id'), table_name='booked_meetings')
    op.drop_table('booked_meetings')
    op.drop_index(op.f('ix_agent_workflows_status'), table_name='agent_workflows')
    op.drop_index(op.f('ix_agent_workflows_lead_id'), table_name='agent_workflows')
    op.drop_table('agent_workflows')
    op.drop_index(op.f('ix_agent_executions_workflow_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_lead_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_type'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
