"""Add pipeline_test_executions table

Revision ID: d282f36fa807
Revises: 20251030_add_oem_tracking_fields
Create Date: 2025-10-31 17:18:19.502527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd282f36fa807'
down_revision: Union[str, None] = '20251030_add_oem_tracking_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_ab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('test_description', sa.Text(), nullable=True),
    sa.Column('variant_a_name', sa.String(length=100), nullable=False),
    sa.Column('variant_b_name', sa.String(length=100), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('participants_a', sa.Integer(), nullable=True),
    sa.Column('participants_b', sa.Integer(), nullable=True),
    sa.Column('conversions_a', sa.Integer(), nullable=True),
    sa.Column('conversions_b', sa.Integer(), nullable=True),
    sa.Column('conversion_rate_a', sa.Float(), nullable=True),
    sa.Column('conversion_rate_b', sa.Float(), nullable=True),
    sa.Column('statistical_significance', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_ab_test_status', 'analytics_ab_tests', ['status', 'start_date'], unique=False)
    op.create_index(op.f('ix_analytics_ab_tests_id'), 'analytics_ab_tests', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_ab_tests_status'), 'analytics_ab_tests', ['status'], unique=False)
    op.create_index(op.f('ix_analytics_ab_tests_test_id'), 'analytics_ab_tests', ['test_id'], unique=True)
    op.create_index(op.f('ix_analytics_ab_tests_test_type'), 'analytics_ab_tests', ['test_type'], unique=False)
    op.create_table('analytics_campaign_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('leads_generated', sa.Integer(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('cost_per_click', sa.Float(), nullable=True),
    sa.Column('cost_per_conversion', sa.Float(), nullable=True),
    sa.Column('revenue_generated', sa.Float(), nullable=True),
    sa.Column('roi_percentage', sa.Float(), nullable=True),
    sa.Column('campaign_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('campaign_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('campaign_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_campaign_type_time', 'analytics_campaign_metrics', ['campaign_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_campaign_metrics_campaign_id'), 'analytics_campaign_metrics', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_analytics_campaign_metrics_campaign_type'), 'analytics_campaign_metrics', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_analytics_campaign_metrics_id'), 'analytics_campaign_metrics', ['id'], unique=False)
    op.create_table('analytics_lead_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('external_lead_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('qualification_score', sa.Float(), nullable=True),
    sa.Column('qualification_tier', sa.String(length=10), nullable=True),
    sa.Column('qualification_reasoning', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('agents_used', sa.JSON(), nullable=True),
    sa.Column('enrichment_sources', sa.JSON(), nullable=True),
    sa.Column('conversion_status', sa.String(length=50), nullable=True),
    sa.Column('conversion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revenue_attributed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_lead_conversion', 'analytics_lead_metrics', ['conversion_status', 'conversion_date'], unique=False)
    op.create_index('idx_analytics_lead_source_time', 'analytics_lead_metrics', ['source', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_campaign_id'), 'analytics_lead_metrics', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_conversion_status'), 'analytics_lead_metrics', ['conversion_status'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_external_lead_id'), 'analytics_lead_metrics', ['external_lead_id'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_id'), 'analytics_lead_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_lead_id'), 'analytics_lead_metrics', ['lead_id'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_qualification_score'), 'analytics_lead_metrics', ['qualification_score'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_qualification_tier'), 'analytics_lead_metrics', ['qualification_tier'], unique=False)
    op.create_index(op.f('ix_analytics_lead_metrics_source'), 'analytics_lead_metrics', ['source'], unique=False)
    op.create_table('analytics_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('report_name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_parameters', sa.JSON(), nullable=True),
    sa.Column('time_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('chart_configs', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_report_type_time', 'analytics_reports', ['report_type', 'generated_at'], unique=False)
    op.create_index(op.f('ix_analytics_reports_id'), 'analytics_reports', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_reports_report_id'), 'analytics_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_analytics_reports_report_type'), 'analytics_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_analytics_reports_status'), 'analytics_reports', ['status'], unique=False)
    op.create_table('analytics_system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_system_category_time', 'analytics_system_metrics', ['category', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_analytics_system_metrics_agent_type'), 'analytics_system_metrics', ['agent_type'], unique=False)
    op.create_index(op.f('ix_analytics_system_metrics_category'), 'analytics_system_metrics', ['category'], unique=False)
    op.create_index(op.f('ix_analytics_system_metrics_endpoint'), 'analytics_system_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_analytics_system_metrics_id'), 'analytics_system_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_system_metrics_metric_name'), 'analytics_system_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_analytics_system_metrics_recorded_at'), 'analytics_system_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_analytics_system_metrics_subcategory'), 'analytics_system_metrics', ['subcategory'], unique=False)
    op.create_table('analytics_user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('api_calls_count', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('agents_used', sa.JSON(), nullable=True),
    sa.Column('leads_processed', sa.Integer(), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_session_user_time', 'analytics_user_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_analytics_user_sessions_id'), 'analytics_user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_user_sessions_session_id'), 'analytics_user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_analytics_user_sessions_user_id'), 'analytics_user_sessions', ['user_id'], unique=False)
    op.create_table('battle_card_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('card_type', sa.Enum('PRICING', 'COMPETITOR', 'FEATURE', 'OBJECTION', 'CASE_STUDY', 'TECHNICAL', 'GENERAL', name='battlecardtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('talking_points', sa.JSON(), nullable=True),
    sa.Column('response_template', sa.Text(), nullable=True),
    sa.Column('trigger_keywords', sa.JSON(), nullable=False),
    sa.Column('trigger_phrases', sa.JSON(), nullable=True),
    sa.Column('trigger_topics', sa.JSON(), nullable=True),
    sa.Column('times_triggered', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('average_helpfulness_score', sa.Float(), nullable=True),
    sa.Column('usage_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_battle_card_templates_card_type', 'battle_card_templates', ['card_type'], unique=False)
    op.create_index('ix_battle_card_templates_is_active', 'battle_card_templates', ['is_active'], unique=False)
    op.create_index('ix_battle_card_templates_priority', 'battle_card_templates', ['priority'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'LINKEDIN', 'SMS', 'CUSTOM', name='campaignchannel'), nullable=False),
    sa.Column('min_qualification_score', sa.Float(), nullable=True),
    sa.Column('target_industries', sa.JSON(), nullable=True),
    sa.Column('target_company_sizes', sa.JSON(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('custom_context', sa.Text(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_delivered', sa.Integer(), nullable=True),
    sa.Column('total_opened', sa.Integer(), nullable=True),
    sa.Column('total_clicked', sa.Integer(), nullable=True),
    sa.Column('total_replied', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('total_cost >= 0', name='check_positive_cost'),
    sa.CheckConstraint('total_sent <= total_messages', name='check_sent_messages'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_status_channel', 'campaigns', ['status', 'channel'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('cerebras_api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('input_cost_usd', sa.Float(), nullable=True),
    sa.Column('output_cost_usd', sa.Float(), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerebras_api_calls_cache_hit'), 'cerebras_api_calls', ['cache_hit'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_created_at'), 'cerebras_api_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_endpoint'), 'cerebras_api_calls', ['endpoint'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_id'), 'cerebras_api_calls', ['id'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_model'), 'cerebras_api_calls', ['model'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_operation_type'), 'cerebras_api_calls', ['operation_type'], unique=False)
    op.create_index(op.f('ix_cerebras_api_calls_success'), 'cerebras_api_calls', ['success'], unique=False)
    op.create_table('crm_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('enrichment_data', sa.JSON(), nullable=True),
    sa.Column('enrichment_score', sa.Float(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_contact_company', 'crm_contacts', ['company'], unique=False)
    op.create_index('idx_crm_contact_email', 'crm_contacts', ['email'], unique=False)
    op.create_index('idx_crm_contact_last_synced', 'crm_contacts', ['last_synced_at'], unique=False)
    op.create_index('idx_crm_contact_source', 'crm_contacts', ['source_platform'], unique=False)
    op.create_index('idx_crm_contact_sync_status', 'crm_contacts', ['sync_status'], unique=False)
    op.create_index(op.f('ix_crm_contacts_company'), 'crm_contacts', ['company'], unique=False)
    op.create_index(op.f('ix_crm_contacts_email'), 'crm_contacts', ['email'], unique=True)
    op.create_index(op.f('ix_crm_contacts_id'), 'crm_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_source_platform'), 'crm_contacts', ['source_platform'], unique=False)
    op.create_index(op.f('ix_crm_contacts_sync_status'), 'crm_contacts', ['sync_status'], unique=False)
    op.create_table('crm_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_auth_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_creds_active', 'crm_credentials', ['is_active', 'platform'], unique=False)
    op.create_index('idx_crm_creds_platform_user', 'crm_credentials', ['platform', 'user_id'], unique=False)
    op.create_index(op.f('ix_crm_credentials_id'), 'crm_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_crm_credentials_is_active'), 'crm_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_crm_credentials_platform'), 'crm_credentials', ['platform'], unique=False)
    op.create_index(op.f('ix_crm_credentials_user_id'), 'crm_credentials', ['user_id'], unique=False)
    op.create_table('crm_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_event_id', 'crm_webhooks', ['event_id'], unique=False)
    op.create_index('idx_webhook_platform_type', 'crm_webhooks', ['platform', 'event_type'], unique=False)
    op.create_index('idx_webhook_processed', 'crm_webhooks', ['processed', 'received_at'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_contact_id'), 'crm_webhooks', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_event_id'), 'crm_webhooks', ['event_id'], unique=True)
    op.create_index(op.f('ix_crm_webhooks_event_timestamp'), 'crm_webhooks', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_event_type'), 'crm_webhooks', ['event_type'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_id'), 'crm_webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_platform'), 'crm_webhooks', ['platform'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_processed'), 'crm_webhooks', ['processed'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_received_at'), 'crm_webhooks', ['received_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('api_key_hash', sa.String(length=256), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=200), nullable=True),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_api_key'), 'customers', ['api_key'], unique=True)
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('langgraph_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('graph_type', sa.String(length=20), nullable=False),
    sa.Column('nodes_executed', sa.JSON(), nullable=True),
    sa.Column('checkpoint_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_langgraph_execution_agent_status', 'langgraph_executions', ['agent_type', 'status'], unique=False)
    op.create_index('idx_langgraph_execution_thread', 'langgraph_executions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_langgraph_executions_agent_type'), 'langgraph_executions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_langgraph_executions_execution_id'), 'langgraph_executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_langgraph_executions_id'), 'langgraph_executions', ['id'], unique=False)
    op.create_index(op.f('ix_langgraph_executions_status'), 'langgraph_executions', ['status'], unique=False)
    op.create_index(op.f('ix_langgraph_executions_thread_id'), 'langgraph_executions', ['thread_id'], unique=False)
    op.create_table('pipeline_test_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_name', sa.String(length=255), nullable=False),
    sa.Column('lead_email', sa.String(length=255), nullable=True),
    sa.Column('lead_phone', sa.String(length=50), nullable=True),
    sa.Column('csv_index', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('stages_json', sa.JSON(), nullable=True),
    sa.Column('stop_on_duplicate', sa.Boolean(), nullable=True),
    sa.Column('skip_enrichment', sa.Boolean(), nullable=True),
    sa.Column('create_in_crm', sa.Boolean(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_test_lead_created', 'pipeline_test_executions', ['lead_name', 'created_at'], unique=False)
    op.create_index('idx_pipeline_test_success', 'pipeline_test_executions', ['success', 'created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_test_executions_created_at'), 'pipeline_test_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_test_executions_id'), 'pipeline_test_executions', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_test_executions_lead_name'), 'pipeline_test_executions', ['lead_name'], unique=False)
    op.create_index(op.f('ix_pipeline_test_executions_success'), 'pipeline_test_executions', ['success'], unique=False)
    op.create_table('voice_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('voice_name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('default_emotion', sa.String(), nullable=True),
    sa.Column('default_speed', sa.String(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('encoding', sa.String(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('average_satisfaction', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_voice_configurations_is_active', 'voice_configurations', ['is_active'], unique=False)
    op.create_index('ix_voice_configurations_name', 'voice_configurations', ['name'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='agent_execution_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_type'), 'agent_executions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_executions_id'), 'agent_executions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_executions_lead_id'), 'agent_executions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_executions_workflow_id'), 'agent_executions', ['workflow_id'], unique=False)
    op.create_table('agent_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='agent_workflow_status'), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_workflows_lead_id'), 'agent_workflows', ['lead_id'], unique=False)
    op.create_index(op.f('ix_agent_workflows_status'), 'agent_workflows', ['status'], unique=False)
    op.create_table('booked_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('calendar_link', sa.String(length=500), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('hubspot_meeting_id', sa.String(length=100), nullable=True),
    sa.Column('calendly_event_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_meetings_calendly_event_id'), 'booked_meetings', ['calendly_event_id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_hubspot_meeting_id'), 'booked_meetings', ['hubspot_meeting_id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_id'), 'booked_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_lead_id'), 'booked_meetings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_booked_meetings_scheduled_time'), 'booked_meetings', ['scheduled_time'], unique=False)
    op.create_table('campaign_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('selected_variant', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'REPLIED', 'BOUNCED', 'FAILED', name='messagestatus'), nullable=False),
    sa.Column('personalization_data', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('generation_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('generation_cost >= 0', name='check_positive_generation_cost'),
    sa.CheckConstraint('selected_variant >= 0 AND selected_variant <= 2', name='check_variant_range'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_message_status', 'campaign_messages', ['campaign_id', 'status'], unique=False)
    op.create_index('idx_message_lead', 'campaign_messages', ['lead_id', 'status'], unique=False)
    op.create_index(op.f('ix_campaign_messages_campaign_id'), 'campaign_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_id'), 'campaign_messages', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_lead_id'), 'campaign_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_campaign_messages_status'), 'campaign_messages', ['status'], unique=False)
    op.create_table('contact_social_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_headline', sa.String(length=500), nullable=True),
    sa.Column('linkedin_location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_connections', sa.String(length=50), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('current_title', sa.String(length=255), nullable=True),
    sa.Column('tenure', sa.String(length=100), nullable=True),
    sa.Column('decision_maker_score', sa.Integer(), nullable=True),
    sa.Column('contact_priority', sa.String(length=20), nullable=True),
    sa.Column('is_c_level', sa.Boolean(), nullable=True),
    sa.Column('is_vp_level', sa.Boolean(), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_username', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('work_history', sa.JSON(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engagement_frequency', sa.String(length=50), nullable=True),
    sa.Column('topics_discussed', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraping_method', sa.String(length=100), nullable=True),
    sa.Column('data_quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_social_profiles_company_name'), 'contact_social_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_contact_email'), 'contact_social_profiles', ['contact_email'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_contact_name'), 'contact_social_profiles', ['contact_name'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_id'), 'contact_social_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_linkedin_url'), 'contact_social_profiles', ['linkedin_url'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'ERROR', 'ABANDONED', name='conversationstatus'), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_audio_seconds', sa.Float(), nullable=True),
    sa.Column('audio_quality_score', sa.Float(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('agent_turns', sa.Integer(), nullable=True),
    sa.Column('prospect_turns', sa.Integer(), nullable=True),
    sa.Column('overall_sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'MIXED', name='sentimenttype'), nullable=True),
    sa.Column('average_sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_trend', sa.String(), nullable=True),
    sa.Column('detected_topics', sa.JSON(), nullable=True),
    sa.Column('key_objections', sa.JSON(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('total_suggestions_shown', sa.Integer(), nullable=True),
    sa.Column('total_suggestions_used', sa.Integer(), nullable=True),
    sa.Column('suggestion_usage_rate', sa.Float(), nullable=True),
    sa.Column('total_battle_cards_shown', sa.Integer(), nullable=True),
    sa.Column('total_battle_cards_used', sa.Integer(), nullable=True),
    sa.Column('battle_card_usage_rate', sa.Float(), nullable=True),
    sa.Column('average_transcription_latency_ms', sa.Integer(), nullable=True),
    sa.Column('average_analysis_latency_ms', sa.Integer(), nullable=True),
    sa.Column('average_total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('final_outcome', sa.String(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_lead_id', 'conversations', ['lead_id'], unique=False)
    op.create_index('ix_conversations_overall_sentiment', 'conversations', ['overall_sentiment'], unique=False)
    op.create_index('ix_conversations_started_at', 'conversations', ['started_at'], unique=False)
    op.create_index('ix_conversations_status', 'conversations', ['status'], unique=False)
    op.create_table('crm_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('contacts_processed', sa.Integer(), nullable=True),
    sa.Column('contacts_created', sa.Integer(), nullable=True),
    sa.Column('contacts_updated', sa.Integer(), nullable=True),
    sa.Column('contacts_failed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['crm_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_log_platform_status', 'crm_sync_logs', ['platform', 'status'], unique=False)
    op.create_index('idx_sync_log_started', 'crm_sync_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_credential_id'), 'crm_sync_logs', ['credential_id'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_id'), 'crm_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_platform'), 'crm_sync_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_started_at'), 'crm_sync_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_status'), 'crm_sync_logs', ['status'], unique=False)
    op.create_table('customer_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.String(length=100), nullable=True),
    sa.Column('deployment_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('failed_tasks', sa.Integer(), nullable=True),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_api_calls', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_agents_customer_id'), 'customer_agents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_agents_deployment_id'), 'customer_agents', ['deployment_id'], unique=True)
    op.create_index(op.f('ix_customer_agents_id'), 'customer_agents', ['id'], unique=False)
    op.create_index(op.f('ix_customer_agents_status'), 'customer_agents', ['status'], unique=False)
    op.create_table('customer_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('max_api_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('api_calls_today', sa.Integer(), nullable=True),
    sa.Column('api_calls_this_month', sa.Integer(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_agents', sa.Integer(), nullable=True),
    sa.Column('active_agents_count', sa.Integer(), nullable=True),
    sa.Column('max_leads_per_month', sa.Integer(), nullable=True),
    sa.Column('leads_this_month', sa.Integer(), nullable=True),
    sa.Column('max_storage_mb', sa.Integer(), nullable=True),
    sa.Column('storage_used_mb', sa.Float(), nullable=True),
    sa.Column('max_documents', sa.Integer(), nullable=True),
    sa.Column('documents_count', sa.Integer(), nullable=True),
    sa.Column('max_cost_per_month_usd', sa.Float(), nullable=True),
    sa.Column('cost_this_month_usd', sa.Float(), nullable=True),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('last_daily_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_monthly_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_quotas_customer_id'), 'customer_quotas', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customer_quotas_id'), 'customer_quotas', ['id'], unique=False)
    op.create_table('enriched_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.BigInteger(), nullable=True),
    sa.Column('funding_total', sa.BigInteger(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('decision_makers', sa.JSON(), nullable=True),
    sa.Column('enrichment_source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enriched_leads_id'), 'enriched_leads', ['id'], unique=False)
    op.create_index(op.f('ix_enriched_leads_lead_id'), 'enriched_leads', ['lead_id'], unique=True)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('runpod_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('runpod_url', sa.String(length=2000), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('target_industries', sa.JSON(), nullable=True),
    sa.Column('company_sizes', sa.JSON(), nullable=True),
    sa.Column('decision_makers', sa.JSON(), nullable=True),
    sa.Column('target_regions', sa.JSON(), nullable=True),
    sa.Column('icp_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_items', sa.JSON(), nullable=True),
    sa.Column('page_gists', sa.JSON(), nullable=True),
    sa.Column('page_metadata', sa.JSON(), nullable=True),
    sa.Column('analysis_status', sa.String(length=50), nullable=True),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_customer_id'), 'knowledge_documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_document_id'), 'knowledge_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_table('langgraph_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_data', sa.JSON(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['langgraph_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_langgraph_checkpoint_thread', 'langgraph_checkpoints', ['thread_id'], unique=False)
    op.create_index(op.f('ix_langgraph_checkpoints_checkpoint_id'), 'langgraph_checkpoints', ['checkpoint_id'], unique=True)
    op.create_index(op.f('ix_langgraph_checkpoints_id'), 'langgraph_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_langgraph_checkpoints_thread_id'), 'langgraph_checkpoints', ['thread_id'], unique=False)
    op.create_table('langgraph_tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_type', sa.String(length=50), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['langgraph_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_langgraph_tool_execution', 'langgraph_tool_calls', ['execution_id'], unique=False)
    op.create_index('idx_langgraph_tool_name_type', 'langgraph_tool_calls', ['tool_name', 'tool_type'], unique=False)
    op.create_index(op.f('ix_langgraph_tool_calls_id'), 'langgraph_tool_calls', ['id'], unique=False)
    op.create_index(op.f('ix_langgraph_tool_calls_tool_call_id'), 'langgraph_tool_calls', ['tool_call_id'], unique=True)
    op.create_index(op.f('ix_langgraph_tool_calls_tool_name'), 'langgraph_tool_calls', ['tool_name'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('subject_lines', sa.JSON(), nullable=True),
    sa.Column('email_sequences', sa.JSON(), nullable=True),
    sa.Column('linkedin_messages', sa.JSON(), nullable=True),
    sa.Column('predicted_open_rate', sa.Float(), nullable=True),
    sa.Column('predicted_reply_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_campaigns_campaign_type'), 'marketing_campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_id'), 'marketing_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_lead_id'), 'marketing_campaigns', ['lead_id'], unique=False)
    op.create_table('organization_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('hierarchy_data', sa.JSON(), nullable=False),
    sa.Column('total_employees_analyzed', sa.Integer(), nullable=True),
    sa.Column('key_decision_makers_count', sa.Integer(), nullable=True),
    sa.Column('c_level_contacts', sa.JSON(), nullable=True),
    sa.Column('vp_level_contacts', sa.JSON(), nullable=True),
    sa.Column('director_level_contacts', sa.JSON(), nullable=True),
    sa.Column('reporting_relationships', sa.JSON(), nullable=True),
    sa.Column('team_structures', sa.JSON(), nullable=True),
    sa.Column('chart_depth', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_charts_company_linkedin_url'), 'organization_charts', ['company_linkedin_url'], unique=True)
    op.create_index(op.f('ix_organization_charts_company_name'), 'organization_charts', ['company_name'], unique=False)
    op.create_index(op.f('ix_organization_charts_id'), 'organization_charts', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('research_data', sa.JSON(), nullable=True),
    sa.Column('insights_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_lead_id'), 'reports', ['lead_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('social_media_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('post_url', sa.String(length=1000), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('retweets_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_reasoning', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_activity_company_name'), 'social_media_activity', ['company_name'], unique=False)
    op.create_index(op.f('ix_social_media_activity_id'), 'social_media_activity', ['id'], unique=False)
    op.create_index(op.f('ix_social_media_activity_platform'), 'social_media_activity', ['platform'], unique=False)
    op.create_index(op.f('ix_social_media_activity_platform_post_id'), 'social_media_activity', ['platform_post_id'], unique=True)
    op.create_table('voice_session_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('voice_name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('initial_emotion', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ERROR', 'ABANDONED', name='voicesessionstatus'), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('min_latency_ms', sa.Integer(), nullable=True),
    sa.Column('max_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=True),
    sa.Column('target_compliance_rate', sa.Float(), nullable=True),
    sa.Column('total_tts_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_stt_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_inference_cost_usd', sa.Float(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('final_outcome', sa.String(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_session_logs_created_at', 'voice_session_logs', ['created_at'], unique=False)
    op.create_index('ix_voice_session_logs_lead_id', 'voice_session_logs', ['lead_id'], unique=False)
    op.create_index('ix_voice_session_logs_status', 'voice_session_logs', ['status'], unique=False)
    op.create_table('conversation_battle_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('card_type', sa.Enum('PRICING', 'COMPETITOR', 'FEATURE', 'OBJECTION', 'CASE_STUDY', 'TECHNICAL', 'GENERAL', name='battlecardtype'), nullable=False),
    sa.Column('trigger_keyword', sa.String(), nullable=True),
    sa.Column('trigger_turn_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('talking_points', sa.JSON(), nullable=True),
    sa.Column('response_template', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('time_to_view_seconds', sa.Integer(), nullable=True),
    sa.Column('time_to_use_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_battle_cards_card_type', 'conversation_battle_cards', ['card_type'], unique=False)
    op.create_index('ix_conversation_battle_cards_conversation_id', 'conversation_battle_cards', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_battle_cards_suggested_at', 'conversation_battle_cards', ['suggested_at'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.Enum('AGENT', 'PROSPECT', 'SYSTEM', name='speakerrole'), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('transcription_confidence', sa.Float(), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'MIXED', name='sentimenttype'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('detected_emotions', sa.JSON(), nullable=True),
    sa.Column('detected_topics', sa.JSON(), nullable=True),
    sa.Column('detected_keywords', sa.JSON(), nullable=True),
    sa.Column('is_objection', sa.Boolean(), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=True),
    sa.Column('is_commitment', sa.Boolean(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('suggestion_shown', sa.Boolean(), nullable=True),
    sa.Column('suggestion_used', sa.Boolean(), nullable=True),
    sa.Column('suggestion_used_index', sa.Integer(), nullable=True),
    sa.Column('transcription_latency_ms', sa.Integer(), nullable=True),
    sa.Column('sentiment_analysis_latency_ms', sa.Integer(), nullable=True),
    sa.Column('suggestion_generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_turns_conversation_id', 'conversation_turns', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_turns_sentiment', 'conversation_turns', ['sentiment'], unique=False)
    op.create_index('ix_conversation_turns_speaker', 'conversation_turns', ['speaker'], unique=False)
    op.create_index('ix_conversation_turns_started_at', 'conversation_turns', ['started_at'], unique=False)
    op.create_table('message_variant_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('variant_number', sa.Integer(), nullable=False),
    sa.Column('tone', sa.Enum('PROFESSIONAL', 'FRIENDLY', 'DIRECT', name='messagetone'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('times_selected', sa.Integer(), nullable=True),
    sa.Column('times_opened', sa.Integer(), nullable=True),
    sa.Column('times_clicked', sa.Integer(), nullable=True),
    sa.Column('times_replied', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('times_clicked >= 0', name='check_positive_clicked'),
    sa.CheckConstraint('times_opened >= 0', name='check_positive_opened'),
    sa.CheckConstraint('times_replied >= 0', name='check_positive_replied'),
    sa.CheckConstraint('times_selected >= 0', name='check_positive_selected'),
    sa.CheckConstraint('variant_number >= 0 AND variant_number <= 2', name='check_analytics_variant_range'),
    sa.ForeignKeyConstraint(['message_id'], ['campaign_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_variant_analytics', 'message_variant_analytics', ['message_id', 'variant_number'], unique=False)
    op.create_index(op.f('ix_message_variant_analytics_id'), 'message_variant_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_message_variant_analytics_message_id'), 'message_variant_analytics', ['message_id'], unique=False)
    op.create_table('voice_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('user_transcript', sa.Text(), nullable=True),
    sa.Column('user_audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('ai_response_text', sa.Text(), nullable=True),
    sa.Column('ai_audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_emotion', sa.String(), nullable=True),
    sa.Column('response_speed', sa.String(), nullable=True),
    sa.Column('stt_latency_ms', sa.Integer(), nullable=True),
    sa.Column('inference_latency_ms', sa.Integer(), nullable=True),
    sa.Column('tts_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('met_latency_target', sa.Boolean(), nullable=True),
    sa.Column('turn_context', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_session_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_turns_started_at', 'voice_turns', ['started_at'], unique=False)
    op.create_index('ix_voice_turns_total_latency_ms', 'voice_turns', ['total_latency_ms'], unique=False)
    op.create_index('ix_voice_turns_voice_session_id', 'voice_turns', ['voice_session_id'], unique=False)
    op.create_table('cartesia_api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('turn_id', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('characters_processed', sa.Integer(), nullable=True),
    sa.Column('audio_seconds_processed', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['voice_turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_session_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cartesia_api_calls_created_at', 'cartesia_api_calls', ['created_at'], unique=False)
    op.create_index('ix_cartesia_api_calls_operation', 'cartesia_api_calls', ['operation'], unique=False)
    op.create_index('ix_cartesia_api_calls_voice_session_id', 'cartesia_api_calls', ['voice_session_id'], unique=False)
    op.alter_column('leads', 'additional_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('leads', 'oems_certified',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('leads', 'oem_tiers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_leads_company_name', table_name='leads')
    op.drop_index('idx_leads_contact_email', table_name='leads')
    op.drop_index('idx_leads_mep_e_score', table_name='leads')
    op.drop_index('idx_leads_qualification_score', table_name='leads')
    op.drop_index('idx_leads_total_oem_count', table_name='leads')
    op.create_index(op.f('ix_leads_company_name'), 'leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_leads_contact_email'), 'leads', ['contact_email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_qualification_score'), 'leads', ['qualification_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_qualification_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_name'), table_name='leads')
    op.create_index('idx_leads_total_oem_count', 'leads', ['total_oem_count'], unique=False)
    op.create_index('idx_leads_qualification_score', 'leads', ['qualification_score'], unique=False)
    op.create_index('idx_leads_mep_e_score', 'leads', ['mep_e_score'], unique=False)
    op.create_index('idx_leads_contact_email', 'leads', ['contact_email'], unique=False)
    op.create_index('idx_leads_company_name', 'leads', ['company_name'], unique=False)
    op.alter_column('leads', 'oem_tiers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('leads', 'oems_certified',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('leads', 'additional_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_cartesia_api_calls_voice_session_id', table_name='cartesia_api_calls')
    op.drop_index('ix_cartesia_api_calls_operation', table_name='cartesia_api_calls')
    op.drop_index('ix_cartesia_api_calls_created_at', table_name='cartesia_api_calls')
    op.drop_table('cartesia_api_calls')
    op.drop_index('ix_voice_turns_voice_session_id', table_name='voice_turns')
    op.drop_index('ix_voice_turns_total_latency_ms', table_name='voice_turns')
    op.drop_index('ix_voice_turns_started_at', table_name='voice_turns')
    op.drop_table('voice_turns')
    op.drop_index(op.f('ix_message_variant_analytics_message_id'), table_name='message_variant_analytics')
    op.drop_index(op.f('ix_message_variant_analytics_id'), table_name='message_variant_analytics')
    op.drop_index('idx_variant_analytics', table_name='message_variant_analytics')
    op.drop_table('message_variant_analytics')
    op.drop_index('ix_conversation_turns_started_at', table_name='conversation_turns')
    op.drop_index('ix_conversation_turns_speaker', table_name='conversation_turns')
    op.drop_index('ix_conversation_turns_sentiment', table_name='conversation_turns')
    op.drop_index('ix_conversation_turns_conversation_id', table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index('ix_conversation_battle_cards_suggested_at', table_name='conversation_battle_cards')
    op.drop_index('ix_conversation_battle_cards_conversation_id', table_name='conversation_battle_cards')
    op.drop_index('ix_conversation_battle_cards_card_type', table_name='conversation_battle_cards')
    op.drop_table('conversation_battle_cards')
    op.drop_index('ix_voice_session_logs_status', table_name='voice_session_logs')
    op.drop_index('ix_voice_session_logs_lead_id', table_name='voice_session_logs')
    op.drop_index('ix_voice_session_logs_created_at', table_name='voice_session_logs')
    op.drop_table('voice_session_logs')
    op.drop_index(op.f('ix_social_media_activity_platform_post_id'), table_name='social_media_activity')
    op.drop_index(op.f('ix_social_media_activity_platform'), table_name='social_media_activity')
    op.drop_index(op.f('ix_social_media_activity_id'), table_name='social_media_activity')
    op.drop_index(op.f('ix_social_media_activity_company_name'), table_name='social_media_activity')
    op.drop_table('social_media_activity')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_lead_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_organization_charts_id'), table_name='organization_charts')
    op.drop_index(op.f('ix_organization_charts_company_name'), table_name='organization_charts')
    op.drop_index(op.f('ix_organization_charts_company_linkedin_url'), table_name='organization_charts')
    op.drop_table('organization_charts')
    op.drop_index(op.f('ix_marketing_campaigns_lead_id'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_id'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_campaign_type'), table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_langgraph_tool_calls_tool_name'), table_name='langgraph_tool_calls')
    op.drop_index(op.f('ix_langgraph_tool_calls_tool_call_id'), table_name='langgraph_tool_calls')
    op.drop_index(op.f('ix_langgraph_tool_calls_id'), table_name='langgraph_tool_calls')
    op.drop_index('idx_langgraph_tool_name_type', table_name='langgraph_tool_calls')
    op.drop_index('idx_langgraph_tool_execution', table_name='langgraph_tool_calls')
    op.drop_table('langgraph_tool_calls')
    op.drop_index(op.f('ix_langgraph_checkpoints_thread_id'), table_name='langgraph_checkpoints')
    op.drop_index(op.f('ix_langgraph_checkpoints_id'), table_name='langgraph_checkpoints')
    op.drop_index(op.f('ix_langgraph_checkpoints_checkpoint_id'), table_name='langgraph_checkpoints')
    op.drop_index('idx_langgraph_checkpoint_thread', table_name='langgraph_checkpoints')
    op.drop_table('langgraph_checkpoints')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_document_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_customer_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_enriched_leads_lead_id'), table_name='enriched_leads')
    op.drop_index(op.f('ix_enriched_leads_id'), table_name='enriched_leads')
    op.drop_table('enriched_leads')
    op.drop_index(op.f('ix_customer_quotas_id'), table_name='customer_quotas')
    op.drop_index(op.f('ix_customer_quotas_customer_id'), table_name='customer_quotas')
    op.drop_table('customer_quotas')
    op.drop_index(op.f('ix_customer_agents_status'), table_name='customer_agents')
    op.drop_index(op.f('ix_customer_agents_id'), table_name='customer_agents')
    op.drop_index(op.f('ix_customer_agents_deployment_id'), table_name='customer_agents')
    op.drop_index(op.f('ix_customer_agents_customer_id'), table_name='customer_agents')
    op.drop_table('customer_agents')
    op.drop_index(op.f('ix_crm_sync_logs_status'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_started_at'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_platform'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_id'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_credential_id'), table_name='crm_sync_logs')
    op.drop_index('idx_sync_log_started', table_name='crm_sync_logs')
    op.drop_index('idx_sync_log_platform_status', table_name='crm_sync_logs')
    op.drop_table('crm_sync_logs')
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.drop_index('ix_conversations_started_at', table_name='conversations')
    op.drop_index('ix_conversations_overall_sentiment', table_name='conversations')
    op.drop_index('ix_conversations_lead_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contact_social_profiles_linkedin_url'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_id'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_contact_name'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_contact_email'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_company_name'), table_name='contact_social_profiles')
    op.drop_table('contact_social_profiles')
    op.drop_index(op.f('ix_campaign_messages_status'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_lead_id'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_id'), table_name='campaign_messages')
    op.drop_index(op.f('ix_campaign_messages_campaign_id'), table_name='campaign_messages')
    op.drop_index('idx_message_lead', table_name='campaign_messages')
    op.drop_index('idx_campaign_message_status', table_name='campaign_messages')
    op.drop_table('campaign_messages')
    op.drop_index(op.f('ix_booked_meetings_scheduled_time'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_lead_id'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_id'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_hubspot_meeting_id'), table_name='booked_meetings')
    op.drop_index(op.f('ix_booked_meetings_calendly_event_id'), table_name='booked_meetings')
    op.drop_table('booked_meetings')
    op.drop_index(op.f('ix_agent_workflows_status'), table_name='agent_workflows')
    op.drop_index(op.f('ix_agent_workflows_lead_id'), table_name='agent_workflows')
    op.drop_table('agent_workflows')
    op.drop_index(op.f('ix_agent_executions_workflow_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_lead_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_type'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index('ix_voice_configurations_name', table_name='voice_configurations')
    op.drop_index('ix_voice_configurations_is_active', table_name='voice_configurations')
    op.drop_table('voice_configurations')
    op.drop_index(op.f('ix_pipeline_test_executions_success'), table_name='pipeline_test_executions')
    op.drop_index(op.f('ix_pipeline_test_executions_lead_name'), table_name='pipeline_test_executions')
    op.drop_index(op.f('ix_pipeline_test_executions_id'), table_name='pipeline_test_executions')
    op.drop_index(op.f('ix_pipeline_test_executions_created_at'), table_name='pipeline_test_executions')
    op.drop_index('idx_pipeline_test_success', table_name='pipeline_test_executions')
    op.drop_index('idx_pipeline_test_lead_created', table_name='pipeline_test_executions')
    op.drop_table('pipeline_test_executions')
    op.drop_index(op.f('ix_langgraph_executions_thread_id'), table_name='langgraph_executions')
    op.drop_index(op.f('ix_langgraph_executions_status'), table_name='langgraph_executions')
    op.drop_index(op.f('ix_langgraph_executions_id'), table_name='langgraph_executions')
    op.drop_index(op.f('ix_langgraph_executions_execution_id'), table_name='langgraph_executions')
    op.drop_index(op.f('ix_langgraph_executions_agent_type'), table_name='langgraph_executions')
    op.drop_index('idx_langgraph_execution_thread', table_name='langgraph_executions')
    op.drop_index('idx_langgraph_execution_agent_status', table_name='langgraph_executions')
    op.drop_table('langgraph_executions')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_api_key'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_crm_webhooks_received_at'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_processed'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_platform'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_id'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_event_type'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_event_timestamp'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_event_id'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_contact_id'), table_name='crm_webhooks')
    op.drop_index('idx_webhook_processed', table_name='crm_webhooks')
    op.drop_index('idx_webhook_platform_type', table_name='crm_webhooks')
    op.drop_index('idx_webhook_event_id', table_name='crm_webhooks')
    op.drop_table('crm_webhooks')
    op.drop_index(op.f('ix_crm_credentials_user_id'), table_name='crm_credentials')
    op.drop_index(op.f('ix_crm_credentials_platform'), table_name='crm_credentials')
    op.drop_index(op.f('ix_crm_credentials_is_active'), table_name='crm_credentials')
    op.drop_index(op.f('ix_crm_credentials_id'), table_name='crm_credentials')
    op.drop_index('idx_crm_creds_platform_user', table_name='crm_credentials')
    op.drop_index('idx_crm_creds_active', table_name='crm_credentials')
    op.drop_table('crm_credentials')
    op.drop_index(op.f('ix_crm_contacts_sync_status'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_source_platform'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_email'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company'), table_name='crm_contacts')
    op.drop_index('idx_crm_contact_sync_status', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_source', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_last_synced', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_email', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_company', table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_cerebras_api_calls_success'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_operation_type'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_model'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_id'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_endpoint'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_created_at'), table_name='cerebras_api_calls')
    op.drop_index(op.f('ix_cerebras_api_calls_cache_hit'), table_name='cerebras_api_calls')
    op.drop_table('cerebras_api_calls')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index('idx_campaign_status_channel', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_battle_card_templates_priority', table_name='battle_card_templates')
    op.drop_index('ix_battle_card_templates_is_active', table_name='battle_card_templates')
    op.drop_index('ix_battle_card_templates_card_type', table_name='battle_card_templates')
    op.drop_table('battle_card_templates')
    op.drop_index(op.f('ix_analytics_user_sessions_user_id'), table_name='analytics_user_sessions')
    op.drop_index(op.f('ix_analytics_user_sessions_session_id'), table_name='analytics_user_sessions')
    op.drop_index(op.f('ix_analytics_user_sessions_id'), table_name='analytics_user_sessions')
    op.drop_index('idx_analytics_session_user_time', table_name='analytics_user_sessions')
    op.drop_table('analytics_user_sessions')
    op.drop_index(op.f('ix_analytics_system_metrics_subcategory'), table_name='analytics_system_metrics')
    op.drop_index(op.f('ix_analytics_system_metrics_recorded_at'), table_name='analytics_system_metrics')
    op.drop_index(op.f('ix_analytics_system_metrics_metric_name'), table_name='analytics_system_metrics')
    op.drop_index(op.f('ix_analytics_system_metrics_id'), table_name='analytics_system_metrics')
    op.drop_index(op.f('ix_analytics_system_metrics_endpoint'), table_name='analytics_system_metrics')
    op.drop_index(op.f('ix_analytics_system_metrics_category'), table_name='analytics_system_metrics')
    op.drop_index(op.f('ix_analytics_system_metrics_agent_type'), table_name='analytics_system_metrics')
    op.drop_index('idx_analytics_system_category_time', table_name='analytics_system_metrics')
    op.drop_table('analytics_system_metrics')
    op.drop_index(op.f('ix_analytics_reports_status'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_report_type'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_report_id'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_id'), table_name='analytics_reports')
    op.drop_index('idx_analytics_report_type_time', table_name='analytics_reports')
    op.drop_table('analytics_reports')
    op.drop_index(op.f('ix_analytics_lead_metrics_source'), table_name='analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_lead_metrics_qualification_tier'), table_name='analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_lead_metrics_qualification_score'), table_name='analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_lead_metrics_lead_id'), table_name='analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_lead_metrics_id'), table_name='analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_lead_metrics_external_lead_id'), table_name='analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_lead_metrics_conversion_status'), table_name='analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_lead_metrics_campaign_id'), table_name='analytics_lead_metrics')
    op.drop_index('idx_analytics_lead_source_time', table_name='analytics_lead_metrics')
    op.drop_index('idx_analytics_lead_conversion', table_name='analytics_lead_metrics')
    op.drop_table('analytics_lead_metrics')
    op.drop_index(op.f('ix_analytics_campaign_metrics_id'), table_name='analytics_campaign_metrics')
    op.drop_index(op.f('ix_analytics_campaign_metrics_campaign_type'), table_name='analytics_campaign_metrics')
    op.drop_index(op.f('ix_analytics_campaign_metrics_campaign_id'), table_name='analytics_campaign_metrics')
    op.drop_index('idx_analytics_campaign_type_time', table_name='analytics_campaign_metrics')
    op.drop_table('analytics_campaign_metrics')
    op.drop_index(op.f('ix_analytics_ab_tests_test_type'), table_name='analytics_ab_tests')
    op.drop_index(op.f('ix_analytics_ab_tests_test_id'), table_name='analytics_ab_tests')
    op.drop_index(op.f('ix_analytics_ab_tests_status'), table_name='analytics_ab_tests')
    op.drop_index(op.f('ix_analytics_ab_tests_id'), table_name='analytics_ab_tests')
    op.drop_index('idx_analytics_ab_test_status', table_name='analytics_ab_tests')
    op.drop_table('analytics_ab_tests')
    # ### end Alembic commands ###
