"""Add CRM integration tables (credentials, contacts, sync_logs, webhooks)

Revision ID: ebf714f5f7b9
Revises: 006_reports_table
Create Date: 2025-10-04 20:03:18.000909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# import pgvector.sqlalchemy  # TODO: Uncomment when pgvector is installed


# revision identifiers, used by Alembic.
revision: str = 'ebf714f5f7b9'
down_revision: Union[str, None] = '006_reports_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: pgvector extension must be installed in PostgreSQL for knowledge_documents table
    # Run: docker exec -it <postgres_container> psql -U sales_agent -d sales_agent_db -c "CREATE EXTENSION IF NOT EXISTS vector"

    op.create_table('crm_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('enrichment_data', sa.JSON(), nullable=True),
    sa.Column('enrichment_score', sa.Float(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_contact_company', 'crm_contacts', ['company'], unique=False)
    op.create_index('idx_crm_contact_email', 'crm_contacts', ['email'], unique=False)
    op.create_index('idx_crm_contact_last_synced', 'crm_contacts', ['last_synced_at'], unique=False)
    op.create_index('idx_crm_contact_source', 'crm_contacts', ['source_platform'], unique=False)
    op.create_index('idx_crm_contact_sync_status', 'crm_contacts', ['sync_status'], unique=False)
    op.create_index(op.f('ix_crm_contacts_company'), 'crm_contacts', ['company'], unique=False)
    op.create_index(op.f('ix_crm_contacts_email'), 'crm_contacts', ['email'], unique=True)
    op.create_index(op.f('ix_crm_contacts_id'), 'crm_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_source_platform'), 'crm_contacts', ['source_platform'], unique=False)
    op.create_index(op.f('ix_crm_contacts_sync_status'), 'crm_contacts', ['sync_status'], unique=False)
    op.create_table('crm_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_auth_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_creds_active', 'crm_credentials', ['is_active', 'platform'], unique=False)
    op.create_index('idx_crm_creds_platform_user', 'crm_credentials', ['platform', 'user_id'], unique=False)
    op.create_index(op.f('ix_crm_credentials_id'), 'crm_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_crm_credentials_is_active'), 'crm_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_crm_credentials_platform'), 'crm_credentials', ['platform'], unique=False)
    op.create_index(op.f('ix_crm_credentials_user_id'), 'crm_credentials', ['user_id'], unique=False)
    op.create_table('crm_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_event_id', 'crm_webhooks', ['event_id'], unique=False)
    op.create_index('idx_webhook_platform_type', 'crm_webhooks', ['platform', 'event_type'], unique=False)
    op.create_index('idx_webhook_processed', 'crm_webhooks', ['processed', 'received_at'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_contact_id'), 'crm_webhooks', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_event_id'), 'crm_webhooks', ['event_id'], unique=True)
    op.create_index(op.f('ix_crm_webhooks_event_timestamp'), 'crm_webhooks', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_event_type'), 'crm_webhooks', ['event_type'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_id'), 'crm_webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_platform'), 'crm_webhooks', ['platform'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_processed'), 'crm_webhooks', ['processed'], unique=False)
    op.create_index(op.f('ix_crm_webhooks_received_at'), 'crm_webhooks', ['received_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('api_key_hash', sa.String(length=256), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=200), nullable=True),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_api_key'), 'customers', ['api_key'], unique=True)
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_firebase_uid'), 'customers', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('voice_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('voice_name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('default_emotion', sa.String(), nullable=True),
    sa.Column('default_speed', sa.String(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('encoding', sa.String(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('average_satisfaction', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_voice_configurations_is_active', 'voice_configurations', ['is_active'], unique=False)
    op.create_index('ix_voice_configurations_name', 'voice_configurations', ['name'], unique=False)
    op.create_table('contact_social_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_headline', sa.String(length=500), nullable=True),
    sa.Column('linkedin_location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_connections', sa.String(length=50), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('current_title', sa.String(length=255), nullable=True),
    sa.Column('tenure', sa.String(length=100), nullable=True),
    sa.Column('decision_maker_score', sa.Integer(), nullable=True),
    sa.Column('contact_priority', sa.String(length=20), nullable=True),
    sa.Column('is_c_level', sa.Boolean(), nullable=True),
    sa.Column('is_vp_level', sa.Boolean(), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_username', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('work_history', sa.JSON(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engagement_frequency', sa.String(length=50), nullable=True),
    sa.Column('topics_discussed', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraping_method', sa.String(length=100), nullable=True),
    sa.Column('data_quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_social_profiles_company_name'), 'contact_social_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_contact_email'), 'contact_social_profiles', ['contact_email'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_contact_name'), 'contact_social_profiles', ['contact_name'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_id'), 'contact_social_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_contact_social_profiles_linkedin_url'), 'contact_social_profiles', ['linkedin_url'], unique=True)
    op.create_table('crm_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('contacts_processed', sa.Integer(), nullable=True),
    sa.Column('contacts_created', sa.Integer(), nullable=True),
    sa.Column('contacts_updated', sa.Integer(), nullable=True),
    sa.Column('contacts_failed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['crm_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_log_platform_status', 'crm_sync_logs', ['platform', 'status'], unique=False)
    op.create_index('idx_sync_log_started', 'crm_sync_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_credential_id'), 'crm_sync_logs', ['credential_id'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_id'), 'crm_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_platform'), 'crm_sync_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_started_at'), 'crm_sync_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crm_sync_logs_status'), 'crm_sync_logs', ['status'], unique=False)
    op.create_table('customer_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.String(length=100), nullable=True),
    sa.Column('deployment_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('failed_tasks', sa.Integer(), nullable=True),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_api_calls', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_agents_customer_id'), 'customer_agents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_agents_deployment_id'), 'customer_agents', ['deployment_id'], unique=True)
    op.create_index(op.f('ix_customer_agents_id'), 'customer_agents', ['id'], unique=False)
    op.create_index(op.f('ix_customer_agents_status'), 'customer_agents', ['status'], unique=False)
    op.create_table('customer_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('max_api_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('api_calls_today', sa.Integer(), nullable=True),
    sa.Column('api_calls_this_month', sa.Integer(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_agents', sa.Integer(), nullable=True),
    sa.Column('active_agents_count', sa.Integer(), nullable=True),
    sa.Column('max_leads_per_month', sa.Integer(), nullable=True),
    sa.Column('leads_this_month', sa.Integer(), nullable=True),
    sa.Column('max_storage_mb', sa.Integer(), nullable=True),
    sa.Column('storage_used_mb', sa.Float(), nullable=True),
    sa.Column('max_documents', sa.Integer(), nullable=True),
    sa.Column('documents_count', sa.Integer(), nullable=True),
    sa.Column('max_cost_per_month_usd', sa.Float(), nullable=True),
    sa.Column('cost_this_month_usd', sa.Float(), nullable=True),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('last_daily_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_monthly_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_quotas_customer_id'), 'customer_quotas', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customer_quotas_id'), 'customer_quotas', ['id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('firebase_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('firebase_url', sa.String(length=2000), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),  # TODO: Change to VECTOR(384) when pgvector is installed
    sa.Column('target_industries', sa.JSON(), nullable=True),
    sa.Column('company_sizes', sa.JSON(), nullable=True),
    sa.Column('decision_makers', sa.JSON(), nullable=True),
    sa.Column('target_regions', sa.JSON(), nullable=True),
    sa.Column('icp_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_customer_id'), 'knowledge_documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_document_id'), 'knowledge_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_table('organization_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('hierarchy_data', sa.JSON(), nullable=False),
    sa.Column('total_employees_analyzed', sa.Integer(), nullable=True),
    sa.Column('key_decision_makers_count', sa.Integer(), nullable=True),
    sa.Column('c_level_contacts', sa.JSON(), nullable=True),
    sa.Column('vp_level_contacts', sa.JSON(), nullable=True),
    sa.Column('director_level_contacts', sa.JSON(), nullable=True),
    sa.Column('reporting_relationships', sa.JSON(), nullable=True),
    sa.Column('team_structures', sa.JSON(), nullable=True),
    sa.Column('chart_depth', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_charts_company_linkedin_url'), 'organization_charts', ['company_linkedin_url'], unique=True)
    op.create_index(op.f('ix_organization_charts_company_name'), 'organization_charts', ['company_name'], unique=False)
    op.create_index(op.f('ix_organization_charts_id'), 'organization_charts', ['id'], unique=False)
    op.create_table('social_media_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('post_url', sa.String(length=1000), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('retweets_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_reasoning', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_activity_company_name'), 'social_media_activity', ['company_name'], unique=False)
    op.create_index(op.f('ix_social_media_activity_id'), 'social_media_activity', ['id'], unique=False)
    op.create_index(op.f('ix_social_media_activity_platform'), 'social_media_activity', ['platform'], unique=False)
    op.create_index(op.f('ix_social_media_activity_platform_post_id'), 'social_media_activity', ['platform_post_id'], unique=True)
    op.create_table('voice_session_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('voice_name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('initial_emotion', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ERROR', 'ABANDONED', name='voicesessionstatus'), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('min_latency_ms', sa.Integer(), nullable=True),
    sa.Column('max_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=True),
    sa.Column('target_compliance_rate', sa.Float(), nullable=True),
    sa.Column('total_tts_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_stt_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_inference_cost_usd', sa.Float(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('final_outcome', sa.String(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_session_logs_created_at', 'voice_session_logs', ['created_at'], unique=False)
    op.create_index('ix_voice_session_logs_lead_id', 'voice_session_logs', ['lead_id'], unique=False)
    op.create_index('ix_voice_session_logs_status', 'voice_session_logs', ['status'], unique=False)
    op.create_table('voice_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('user_transcript', sa.Text(), nullable=True),
    sa.Column('user_audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('ai_response_text', sa.Text(), nullable=True),
    sa.Column('ai_audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_emotion', sa.String(), nullable=True),
    sa.Column('response_speed', sa.String(), nullable=True),
    sa.Column('stt_latency_ms', sa.Integer(), nullable=True),
    sa.Column('inference_latency_ms', sa.Integer(), nullable=True),
    sa.Column('tts_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('met_latency_target', sa.Boolean(), nullable=True),
    sa.Column('turn_context', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_session_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_turns_started_at', 'voice_turns', ['started_at'], unique=False)
    op.create_index('ix_voice_turns_total_latency_ms', 'voice_turns', ['total_latency_ms'], unique=False)
    op.create_index('ix_voice_turns_voice_session_id', 'voice_turns', ['voice_session_id'], unique=False)
    op.create_table('cartesia_api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('turn_id', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('characters_processed', sa.Integer(), nullable=True),
    sa.Column('audio_seconds_processed', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['voice_turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_session_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cartesia_api_calls_created_at', 'cartesia_api_calls', ['created_at'], unique=False)
    op.create_index('ix_cartesia_api_calls_operation', 'cartesia_api_calls', ['operation'], unique=False)
    op.create_index('ix_cartesia_api_calls_voice_session_id', 'cartesia_api_calls', ['voice_session_id'], unique=False)
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.drop_index('ix_leads_industry', table_name='leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_leads_industry', 'leads', ['industry'], unique=False)
    op.create_index('ix_leads_created_at', 'leads', [sa.text('created_at DESC')], unique=False)
    op.drop_index('ix_cartesia_api_calls_voice_session_id', table_name='cartesia_api_calls')
    op.drop_index('ix_cartesia_api_calls_operation', table_name='cartesia_api_calls')
    op.drop_index('ix_cartesia_api_calls_created_at', table_name='cartesia_api_calls')
    op.drop_table('cartesia_api_calls')
    op.drop_index('ix_voice_turns_voice_session_id', table_name='voice_turns')
    op.drop_index('ix_voice_turns_total_latency_ms', table_name='voice_turns')
    op.drop_index('ix_voice_turns_started_at', table_name='voice_turns')
    op.drop_table('voice_turns')
    op.drop_index('ix_voice_session_logs_status', table_name='voice_session_logs')
    op.drop_index('ix_voice_session_logs_lead_id', table_name='voice_session_logs')
    op.drop_index('ix_voice_session_logs_created_at', table_name='voice_session_logs')
    op.drop_table('voice_session_logs')
    op.drop_index(op.f('ix_social_media_activity_platform_post_id'), table_name='social_media_activity')
    op.drop_index(op.f('ix_social_media_activity_platform'), table_name='social_media_activity')
    op.drop_index(op.f('ix_social_media_activity_id'), table_name='social_media_activity')
    op.drop_index(op.f('ix_social_media_activity_company_name'), table_name='social_media_activity')
    op.drop_table('social_media_activity')
    op.drop_index(op.f('ix_organization_charts_id'), table_name='organization_charts')
    op.drop_index(op.f('ix_organization_charts_company_name'), table_name='organization_charts')
    op.drop_index(op.f('ix_organization_charts_company_linkedin_url'), table_name='organization_charts')
    op.drop_table('organization_charts')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_document_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_customer_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_customer_quotas_id'), table_name='customer_quotas')
    op.drop_index(op.f('ix_customer_quotas_customer_id'), table_name='customer_quotas')
    op.drop_table('customer_quotas')
    op.drop_index(op.f('ix_customer_agents_status'), table_name='customer_agents')
    op.drop_index(op.f('ix_customer_agents_id'), table_name='customer_agents')
    op.drop_index(op.f('ix_customer_agents_deployment_id'), table_name='customer_agents')
    op.drop_index(op.f('ix_customer_agents_customer_id'), table_name='customer_agents')
    op.drop_table('customer_agents')
    op.drop_index(op.f('ix_crm_sync_logs_status'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_started_at'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_platform'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_id'), table_name='crm_sync_logs')
    op.drop_index(op.f('ix_crm_sync_logs_credential_id'), table_name='crm_sync_logs')
    op.drop_index('idx_sync_log_started', table_name='crm_sync_logs')
    op.drop_index('idx_sync_log_platform_status', table_name='crm_sync_logs')
    op.drop_table('crm_sync_logs')
    op.drop_index(op.f('ix_contact_social_profiles_linkedin_url'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_id'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_contact_name'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_contact_email'), table_name='contact_social_profiles')
    op.drop_index(op.f('ix_contact_social_profiles_company_name'), table_name='contact_social_profiles')
    op.drop_table('contact_social_profiles')
    op.drop_index('ix_voice_configurations_name', table_name='voice_configurations')
    op.drop_index('ix_voice_configurations_is_active', table_name='voice_configurations')
    op.drop_table('voice_configurations')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_firebase_uid'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_api_key'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_crm_webhooks_received_at'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_processed'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_platform'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_id'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_event_type'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_event_timestamp'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_event_id'), table_name='crm_webhooks')
    op.drop_index(op.f('ix_crm_webhooks_contact_id'), table_name='crm_webhooks')
    op.drop_index('idx_webhook_processed', table_name='crm_webhooks')
    op.drop_index('idx_webhook_platform_type', table_name='crm_webhooks')
    op.drop_index('idx_webhook_event_id', table_name='crm_webhooks')
    op.drop_table('crm_webhooks')
    op.drop_index(op.f('ix_crm_credentials_user_id'), table_name='crm_credentials')
    op.drop_index(op.f('ix_crm_credentials_platform'), table_name='crm_credentials')
    op.drop_index(op.f('ix_crm_credentials_is_active'), table_name='crm_credentials')
    op.drop_index(op.f('ix_crm_credentials_id'), table_name='crm_credentials')
    op.drop_index('idx_crm_creds_platform_user', table_name='crm_credentials')
    op.drop_index('idx_crm_creds_active', table_name='crm_credentials')
    op.drop_table('crm_credentials')
    op.drop_index(op.f('ix_crm_contacts_sync_status'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_source_platform'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_email'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company'), table_name='crm_contacts')
    op.drop_index('idx_crm_contact_sync_status', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_source', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_last_synced', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_email', table_name='crm_contacts')
    op.drop_index('idx_crm_contact_company', table_name='crm_contacts')
    op.drop_table('crm_contacts')
    # ### end Alembic commands ###
