"""
Alert Management API Endpoints

Provides CRUD operations for alerts in Tim's BDR workflow.
Alerts are generated by agents and notify Tim of important events.

Endpoints:
- GET /api/v1/alerts - Alert history (paginated)
- POST /api/v1/alerts/{id}/acknowledge - Mark alert as handled
- GET /api/v1/alerts/unread - Unread count
"""

from fastapi import APIRouter, HTTPException, Depends, Query
from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime
from uuid import uuid4

from app.core.logging import setup_logging
from app.auth.dependencies import get_current_user
from app.api.cockpit_websocket import publish_alert_event

logger = setup_logging(__name__)

router = APIRouter(prefix="/alerts", tags=["alerts"])


# ========== Pydantic Models ==========

class Alert(BaseModel):
    """Alert data model matching dim_alerts schema."""
    id: str  # Maps to alert_id in Supabase
    severity: Literal["low", "medium", "high", "critical"]
    alert_type: str = "general"
    title: str
    message: str
    company_id: Optional[str] = None  # FK to dim_companies
    contact_id: Optional[str] = None  # FK to dim_contacts
    draft_id: Optional[str] = None
    agent_name: Optional[str] = None
    task_id: Optional[str] = None
    metadata: Optional[dict] = None
    created_at: datetime
    acknowledged: bool = False
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None


class AlertAcknowledgeRequest(BaseModel):
    """Request to acknowledge an alert."""
    notes: Optional[str] = Field(
        default=None,
        description="Optional notes about how the alert was handled"
    )


class AlertListResponse(BaseModel):
    """Paginated alert list response."""
    total: int
    page: int
    page_size: int
    alerts: List[Alert]


class UnreadCountResponse(BaseModel):
    """Response with unread alert count."""
    unread_count: int
    critical_count: int
    high_count: int
    medium_count: int
    low_count: int


# ========== Supabase Alert Storage ==========

def _get_supabase():
    """Get Supabase client for alerts."""
    from app.core.supabase_client import get_supabase_client
    return get_supabase_client()


def _row_to_alert(row: dict) -> Alert:
    """Convert Supabase row to Alert model."""
    return Alert(
        id=row['alert_id'],
        severity=row['severity'],
        alert_type=row.get('alert_type', 'general'),
        title=row['title'],
        message=row['message'],
        company_id=row.get('company_id'),
        contact_id=row.get('contact_id'),
        draft_id=row.get('draft_id'),
        agent_name=row.get('agent_name'),
        task_id=row.get('task_id'),
        metadata=row.get('metadata'),
        created_at=datetime.fromisoformat(row['created_at'].replace('Z', '+00:00')),
        acknowledged=row.get('acknowledged', False),
        acknowledged_at=datetime.fromisoformat(row['acknowledged_at'].replace('Z', '+00:00')) if row.get('acknowledged_at') else None,
        acknowledged_by=row.get('acknowledged_by')
    )


def _get_alert_by_id(alert_id: str) -> Optional[Alert]:
    """Get alert by ID from Supabase."""
    try:
        supabase = _get_supabase()
        result = supabase.table('dim_alerts').select('*').eq('alert_id', alert_id).execute()
        if result.data and len(result.data) > 0:
            return _row_to_alert(result.data[0])
        return None
    except Exception as e:
        logger.error(f"Error fetching alert {alert_id}: {e}")
        return None


def _ensure_alerts_table_exists():
    """Check if dim_alerts table exists (for health checks)."""
    try:
        supabase = _get_supabase()
        # Try to select - if table doesn't exist, we'll create it via migration
        supabase.table('dim_alerts').select('alert_id').limit(1).execute()
    except Exception as e:
        logger.warning(f"dim_alerts table may not exist: {e}. Run SQL migration in Supabase.")


# ========== API Endpoints ==========

@router.get("", response_model=AlertListResponse)
async def get_alerts(
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    severity: Optional[str] = Query(default=None),
    acknowledged: Optional[bool] = Query(default=None),
    current_user: dict = Depends(get_current_user),
):
    """
    Get paginated alert history.

    Returns alerts in reverse chronological order (newest first).

    Args:
        page: Page number (1-indexed)
        page_size: Items per page (1-100)
        severity: Filter by severity (low, medium, high, critical)
        acknowledged: Filter by acknowledgement status
        current_user: Authenticated user (required)

    Returns:
        AlertListResponse with paginated alerts

    Example:
        ```bash
        # Get unacknowledged alerts
        curl http://localhost:8001/api/v1/alerts?acknowledged=false \\
          -H "Authorization: Bearer <token>"

        # Get critical alerts
        curl http://localhost:8001/api/v1/alerts?severity=critical \\
          -H "Authorization: Bearer <token>"
        ```
    """
    try:
        supabase = _get_supabase()

        # Build query
        query = supabase.table('dim_alerts').select('*', count='exact')

        # Apply filters
        if severity:
            query = query.eq('severity', severity)
        if acknowledged is not None:
            query = query.eq('acknowledged', acknowledged)

        # Sort and paginate
        query = query.order('created_at', desc=True)
        query = query.range((page - 1) * page_size, page * page_size - 1)

        result = query.execute()

        # Convert to Alert objects using helper
        alerts = [_row_to_alert(row) for row in result.data]

        return AlertListResponse(
            total=result.count or len(alerts),
            page=page,
            page_size=page_size,
            alerts=alerts
        )

    except Exception as e:
        logger.error(f"Failed to get alerts: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to retrieve alerts: {str(e)}"
        )


@router.post("/{alert_id}/acknowledge")
async def acknowledge_alert(
    alert_id: str,
    request: AlertAcknowledgeRequest = AlertAcknowledgeRequest(),
    current_user: dict = Depends(get_current_user),
):
    """
    Mark an alert as acknowledged.

    This indicates that Tim has seen and handled the alert.

    Args:
        alert_id: UUID of the alert
        request: Optional acknowledgement notes
        current_user: Authenticated user (required)

    Returns:
        Updated alert

    Example:
        ```bash
        curl -X POST http://localhost:8001/api/v1/alerts/abc-123/acknowledge \\
          -H "Authorization: Bearer <token>" \\
          -H "Content-Type: application/json" \\
          -d '{"notes": "Called the lead, left voicemail"}'
        ```
    """
    try:
        supabase = _get_supabase()
        acknowledged_by = current_user.get("email", "Unknown")
        acknowledged_at = datetime.utcnow()

        # Update alert in Supabase
        result = supabase.table('dim_alerts').update({
            'acknowledged': True,
            'acknowledged_at': acknowledged_at.isoformat(),
            'acknowledged_by': acknowledged_by,
            'acknowledgement_notes': request.notes
        }).eq('alert_id', alert_id).execute()

        if not result.data or len(result.data) == 0:
            raise HTTPException(
                status_code=404,
                detail=f"Alert not found: {alert_id}"
            )

        logger.info(
            f"Alert {alert_id} acknowledged by {acknowledged_by} - "
            f"notes: {request.notes or 'none'}"
        )

        return {
            "status": "acknowledged",
            "alert_id": alert_id,
            "acknowledged_by": acknowledged_by,
            "acknowledged_at": acknowledged_at.isoformat(),
            "notes": request.notes
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to acknowledge alert {alert_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to acknowledge alert: {str(e)}"
        )


@router.get("/unread", response_model=UnreadCountResponse)
async def get_unread_count(
    current_user: dict = Depends(get_current_user),
):
    """
    Get count of unacknowledged alerts by severity.

    Returns total unread count and breakdown by severity level.

    Args:
        current_user: Authenticated user (required)

    Returns:
        UnreadCountResponse with counts

    Example:
        ```bash
        curl http://localhost:8001/api/v1/alerts/unread \\
          -H "Authorization: Bearer <token>"
        ```
    """
    try:
        supabase = _get_supabase()

        # Query unacknowledged alerts with severity counts
        result = supabase.table('dim_alerts').select('severity').eq('acknowledged', False).execute()

        unread_alerts = result.data or []
        critical_count = sum(1 for a in unread_alerts if a.get('severity') == "critical")
        high_count = sum(1 for a in unread_alerts if a.get('severity') == "high")
        medium_count = sum(1 for a in unread_alerts if a.get('severity') == "medium")
        low_count = sum(1 for a in unread_alerts if a.get('severity') == "low")

        return UnreadCountResponse(
            unread_count=len(unread_alerts),
            critical_count=critical_count,
            high_count=high_count,
            medium_count=medium_count,
            low_count=low_count
        )

    except Exception as e:
        logger.error(f"Failed to get unread count: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to get unread count: {str(e)}"
        )


# ========== Helper Functions ==========

async def create_alert(
    severity: str,
    title: str,
    message: str,
    company_id: Optional[str] = None,
    contact_id: Optional[str] = None,
    draft_id: Optional[str] = None,
    alert_type: str = "general",
    agent_name: Optional[str] = None,
    task_id: Optional[str] = None,
    metadata: Optional[dict] = None,
    broadcast: bool = True
) -> Alert:
    """
    Create a new alert and optionally broadcast to WebSocket clients.

    This function should be called from agents and background tasks
    to notify Tim of important events.

    Args:
        severity: Alert severity (low, medium, high, critical)
        title: Alert title
        message: Alert message
        company_id: Optional related company ID (FK to dim_companies)
        contact_id: Optional related contact ID (FK to dim_contacts)
        draft_id: Optional related draft ID
        alert_type: Category (hot_lead, error, approval, sequence, general)
        agent_name: Which agent generated this alert
        task_id: Celery task ID if applicable
        metadata: Additional context as dict
        broadcast: Whether to broadcast to WebSocket clients (default: True)

    Returns:
        Created alert

    Example (from agent):
        ```python
        from app.api.alerts import create_alert

        # Create alert for HOT lead reply
        alert = await create_alert(
            severity="high",
            title="HOT Lead Reply",
            message="John Smith at Acme Corp replied: interested",
            company_id="company-uuid-123",
            alert_type="hot_lead",
            agent_name="reply_router",
            broadcast=True
        )
        ```
    """
    alert_id = str(uuid4())
    created_at = datetime.utcnow()

    alert = Alert(
        id=alert_id,
        severity=severity,
        alert_type=alert_type,
        title=title,
        message=message,
        company_id=company_id,
        contact_id=contact_id,
        draft_id=draft_id,
        agent_name=agent_name,
        task_id=task_id,
        metadata=metadata,
        created_at=created_at,
        acknowledged=False
    )

    # Store in Supabase
    try:
        supabase = _get_supabase()
        insert_data = {
            'alert_id': alert_id,
            'severity': severity,
            'alert_type': alert_type,
            'title': title,
            'message': message,
            'company_id': company_id,
            'contact_id': contact_id,
            'draft_id': draft_id,
            'agent_name': agent_name,
            'task_id': task_id,
            'metadata': metadata or {},
            'created_at': created_at.isoformat(),
            'acknowledged': False
        }
        # Remove None values for Supabase
        insert_data = {k: v for k, v in insert_data.items() if v is not None}
        supabase.table('dim_alerts').insert(insert_data).execute()
    except Exception as e:
        logger.error(f"Failed to store alert in Supabase: {e}")
        # Continue anyway - alert will still be broadcast via WebSocket

    logger.info(f"Alert created: {severity} - {title} (agent: {agent_name})")

    # Broadcast to WebSocket clients
    if broadcast:
        await publish_alert_event(
            severity=severity,
            title=title,
            message=message,
            lead_id=company_id,  # Map company_id to lead_id for WS compatibility
            draft_id=draft_id
        )

    return alert


# ========== Demo Alert Generator (for testing) ==========

@router.post("/demo/create")
async def create_demo_alert(
    current_user: dict = Depends(get_current_user),
):
    """
    Create a demo alert for testing the UI.

    This endpoint is for development/testing only.

    Args:
        current_user: Authenticated user (required)

    Returns:
        Created demo alert
    """
    demo_alert = await create_alert(
        severity="high",
        title="Demo Alert",
        message="This is a test alert generated via API",
        alert_type="general",
        agent_name="demo_endpoint",
        broadcast=True
    )

    return {
        "status": "created",
        "alert": demo_alert
    }


# ========== Exports ==========

__all__ = [
    "router",
    "Alert",
    "AlertAcknowledgeRequest",
    "AlertListResponse",
    "UnreadCountResponse",
    "create_alert",
]
