-- =============================================================================
-- DIM_ALERTS: BDR Cockpit Alerts (Dec 6, 2025)
-- =============================================================================
-- Alerts generated by autonomous agents for Tim's review in the BDR Cockpit.
-- Examples: HOT lead reply, agent errors, approval requests
-- =============================================================================

-- Drop if exists for clean recreation
DROP TABLE IF EXISTS dim_alerts CASCADE;

CREATE TABLE dim_alerts (
    alert_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Severity and Classification
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    alert_type TEXT DEFAULT 'general',  -- 'hot_lead', 'error', 'approval', 'sequence', 'general'

    -- Content
    title TEXT NOT NULL,
    message TEXT NOT NULL,

    -- Related Entities (nullable FKs to dimension tables)
    company_id UUID REFERENCES dim_companies(company_id) ON DELETE SET NULL,
    contact_id UUID REFERENCES dim_contacts(contact_id) ON DELETE SET NULL,
    draft_id UUID,  -- References dim_ai_drafts if exists

    -- Agent Context
    agent_name TEXT,  -- Which agent generated this alert
    task_id TEXT,     -- Celery task ID if applicable

    -- Metadata
    metadata JSONB DEFAULT '{}',  -- Flexible JSON for extra context

    -- Acknowledgement Tracking
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_at TIMESTAMPTZ,
    acknowledged_by TEXT,
    acknowledgement_notes TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ  -- Optional expiration for time-sensitive alerts
);

-- Indexes for common queries
CREATE INDEX idx_dim_alerts_acknowledged ON dim_alerts(acknowledged);
CREATE INDEX idx_dim_alerts_severity ON dim_alerts(severity);
CREATE INDEX idx_dim_alerts_created_at ON dim_alerts(created_at DESC);
CREATE INDEX idx_dim_alerts_company_id ON dim_alerts(company_id);
CREATE INDEX idx_dim_alerts_alert_type ON dim_alerts(alert_type);
CREATE INDEX idx_dim_alerts_agent ON dim_alerts(agent_name);

-- Unacknowledged alerts (most common query)
CREATE INDEX idx_dim_alerts_unacked ON dim_alerts(created_at DESC)
    WHERE acknowledged = FALSE;

-- Critical unacknowledged alerts (high priority view)
CREATE INDEX idx_dim_alerts_critical_unacked ON dim_alerts(created_at DESC)
    WHERE acknowledged = FALSE AND severity IN ('critical', 'high');

-- Enable RLS
ALTER TABLE dim_alerts ENABLE ROW LEVEL SECURITY;

-- Service role full access
CREATE POLICY "Service role has full access to alerts"
ON dim_alerts
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Authenticated users can read alerts
CREATE POLICY "Authenticated users can read alerts"
ON dim_alerts
FOR SELECT
TO authenticated
USING (true);

-- Authenticated users can update (acknowledge) alerts
CREATE POLICY "Authenticated users can acknowledge alerts"
ON dim_alerts
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- Comments for documentation
COMMENT ON TABLE dim_alerts IS 'BDR Cockpit alerts from autonomous agents - hot leads, errors, approvals needed';
COMMENT ON COLUMN dim_alerts.alert_id IS 'Primary key (UUID)';
COMMENT ON COLUMN dim_alerts.severity IS 'Alert priority: low, medium, high, critical';
COMMENT ON COLUMN dim_alerts.alert_type IS 'Category: hot_lead, error, approval, sequence, general';
COMMENT ON COLUMN dim_alerts.company_id IS 'Optional reference to related company (FK to dim_companies)';
COMMENT ON COLUMN dim_alerts.contact_id IS 'Optional reference to related contact (FK to dim_contacts)';
COMMENT ON COLUMN dim_alerts.draft_id IS 'Optional reference to related BDR draft';
COMMENT ON COLUMN dim_alerts.agent_name IS 'Which autonomous agent generated this alert';
COMMENT ON COLUMN dim_alerts.metadata IS 'Flexible JSON for additional context';
COMMENT ON COLUMN dim_alerts.acknowledged IS 'Whether Tim has seen and handled this alert';
