"""
Close CRM Staging Service - Stage marketing content as drafts (NO actual sends)

This service creates NOTE activities in Close CRM containing staged email/SMS content.
The content is for review only - NO actual emails or SMS messages are sent.

Usage:
    staging = CloseStagingService()
    result = await staging.stage_marketing_content(
        lead_id="lead_xxx",
        marketing_content={"email_subject": "...", "email_content": "...", "sms_content": "..."}
    )

Safety:
    - Uses POST /activity/note/ - notes cannot trigger sends
    - Does NOT use email/sms draft endpoints (to be extra safe)
    - All content is clearly marked as "STAGED - NOT SENT"
"""
import httpx
import logging
import base64
from typing import Dict, Any, Optional
import os

logger = logging.getLogger(__name__)


class CloseStagingService:
    """Stage email/SMS content as notes in Close CRM (NO actual sends)"""

    BASE_URL = "https://api.close.com/api/v1"
    TIM_USER_ID = "user_RCfVbzPJJUMj6HDQ8JGtpBkouK7fMB25X15B08FUpt1"

    def __init__(self):
        api_key = os.getenv("CLOSE_API_KEY")
        if not api_key:
            raise ValueError("CLOSE_API_KEY not set in environment")
        auth_b64 = base64.b64encode(f"{api_key}:".encode()).decode()
        self.auth_header = f"Basic {auth_b64}"

    async def stage_note(
        self,
        lead_id: str,
        email_content: Dict[str, str],
        sms_content: str
    ) -> Dict[str, Any]:
        """
        Create note with all staged content (safest option - notes never send).

        Args:
            lead_id: Close CRM lead ID (e.g., "lead_xxx...")
            email_content: {"subject": "...", "body": "..."}
            sms_content: SMS message text

        Returns:
            {"success": True/False, "activity_id": "...", "type": "note"}
        """
        note = f"""
===========================================
STAGED MARKETING CONTENT (NOT SENT)
===========================================
Generated by sales-agent pipeline
Review and send manually when ready.

EMAIL DRAFT
-------------------------------------------
Subject: {email_content.get('subject', 'N/A')}

{email_content.get('body', 'N/A')}

SMS DRAFT
-------------------------------------------
{sms_content or 'N/A'}

===========================================
This is staged content for review only.
NO emails or SMS have been sent.
===========================================
"""

        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.BASE_URL}/activity/note/",
                    headers={
                        "Authorization": self.auth_header,
                        "Content-Type": "application/json"
                    },
                    json={
                        "lead_id": lead_id,
                        "note": note.strip(),
                        "user_id": self.TIM_USER_ID
                    },
                    timeout=30.0
                )

                if response.status_code >= 400:
                    error_msg = response.text[:500]
                    logger.error(f"Close note failed: {response.status_code} - {error_msg}")
                    return {
                        "success": False,
                        "error": f"HTTP {response.status_code}: {error_msg}",
                        "type": "note"
                    }

                data = response.json()
                activity_id = data.get("id")
                logger.info(f"Staged note created: {activity_id} for lead {lead_id}")

                return {
                    "success": True,
                    "activity_id": activity_id,
                    "type": "note",
                    "lead_id": lead_id
                }

        except httpx.TimeoutException:
            logger.error(f"Timeout staging note for lead {lead_id}")
            return {"success": False, "error": "Request timeout", "type": "note"}
        except Exception as e:
            logger.error(f"Error staging note: {str(e)}")
            return {"success": False, "error": str(e), "type": "note"}

    async def stage_marketing_content(
        self,
        lead_id: str,
        marketing_content: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Stage all marketing content to Close CRM as a note.

        Args:
            lead_id: Close CRM lead ID
            marketing_content: Dict with email_subject, email_content/email_body, sms_content/sms_message

        Returns:
            {"note": {...stage_note result...}}
        """
        results = {}

        # Extract email content (handle both naming conventions)
        email_subject = marketing_content.get("email_subject", "")
        email_body = marketing_content.get("email_content") or marketing_content.get("email_body", "")

        # Extract SMS content (handle both naming conventions)
        sms_content = marketing_content.get("sms_content") or marketing_content.get("sms_message", "")

        # Create note with staged content
        results["note"] = await self.stage_note(
            lead_id=lead_id,
            email_content={
                "subject": email_subject,
                "body": email_body
            },
            sms_content=sms_content
        )

        return results

    async def check_lead_exists(self, lead_id: str) -> bool:
        """
        Verify a lead exists before trying to stage content.

        Args:
            lead_id: Close CRM lead ID

        Returns:
            True if lead exists, False otherwise
        """
        try:
            async with httpx.AsyncClient() as client:
                response = await client.get(
                    f"{self.BASE_URL}/lead/{lead_id}/",
                    headers={"Authorization": self.auth_header},
                    timeout=15.0
                )
                return response.status_code == 200
        except Exception as e:
            logger.error(f"Error checking lead existence: {e}")
            return False
